version: '2'
services:
  risk:
    entrypoint: zsh
    build: .
    environment:
            - SUBJECTS_DIR=/data/derivatives/freesurfer
    volumes:
      - ./risk_experiment:/risk_experiment
      - $DATA_DIR/ds-risk:/data
      - $HOME/freesurfer/license.txt:/opt/freesurfer-6.0.1/license.txt
      - /data/tmp:/tmp
      - ./braincoder:/braincoder
      - ./scripts:/scripts
