version: '2'
services:
  risk:
    entrypoint: zsh
    build: .
    environment:
            - SUBJECTS_DIR=/data/derivatives/freesurfer
    volumes:
      - .:/src
      - /Volumes/Samsung_T5/ds-risk:/data
      - $FREESURFER_HOME/license.txt:/opt/freesurfer-6.0.1/license.txt
      - /tmp:/tmp
